---
fixtures:
  repositories:
    authselect: https://github.com/jcpunk/puppet-authselect
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    oddjob: https://github.com/simp/pupmod-simp-oddjob.git
    pam: https://github.com/simp/pupmod-simp-pam
    simp_authselect: https://github.com/simp/pupmod-simp-simp_authselect
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    simp_authselect: "#{source_dir}"
